from .user import User
from .cv import CV
from .classification_log import ClassificationLog
from .cvprocessingqueue import CVProcessingQueue
from .jobcategory import JobCategory
from .categorystatistic import CategoryStatistic
from .mlmodel import MLModel
from .useractivitylog import UserActivityLog
from .systemlog import SystemLog
