"""Add company_logo to job_postings

Revision ID: cebe1a06f4af
Revises: 8d9529e87369
Create Date: 2025-12-02 22:00:32.093481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cebe1a06f4af'
down_revision = '8d9529e87369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_logo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_column('company_logo')

    # ### end Alembic commands ###
