"""add job_posting relationship to JobApplication22

Revision ID: 1c1f2bccc81c
Revises: e910c1d2e25c
Create Date: 2025-12-03 21:19:57.599581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1f2bccc81c'
down_revision = 'e910c1d2e25c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.alter_column('job_posting_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.alter_column('job_posting_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
