"""add job_posting relationship to JobApplication

Revision ID: e910c1d2e25c
Revises: 9e22568df081
Create Date: 2025-12-03 21:16:20.575183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e910c1d2e25c'
down_revision = '9e22568df081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.alter_column('job_posting_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.alter_column('job_posting_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
